### ISSUE TITLE
Subscriptions page

### ISSUE THREAD

**Issue by marektucek** [closerdao/closer-ui#108]

**Comment by marektucek** [comment]
**User story:**
As a user , I want to have the ability to select a TDF subscription tier from a list so that I can reap the benefits of it.

**Scenario 1, or Acceptance criteria 1**
When an Unauthenticated user goes to /subscription page
He could see 4 options. And he could click the "Buy" button under each option to proceed to checkout.

Each of the options includes:

subscription name
- detail 1
- ....
- detail X
- price
- button "Buy me"

Variations:
When a user clicks the button "Buy" he is redirected to Stripe-hosted checkout.
or
the magic modal appears which contains 2 buttons - confirm and cancel.
or
a special section is rendered with the input for the credit card."

Analytics:

track /subsriptio page opens
track clicks on each subscription.
track clicks on "more" button

https://www.figma.com/file/CCJglfs7fIzNpJwlEPSsLD/%F0%9F%A6%84-Communication?node-id=3285-5733&t=RZuXDhZBRpt246u9-0 (frame Subscription options)

**Scenario 2, or Acceptance criteria 2**
Unauthenticated user is on the event page - https://www.traditionaldreamfactory.com/events/tdf-is-turning-2,
And he clicks on "Buy ticket", proceed to checkout where he sees an option "Buy this as part of the Premium subscription".

After he clicks, he gets redirected to the Subscription page where he can choose the tier and subscribe.

**Comment by marektucek** [comment]
preview at https://traditionaldreamfactory-git-subscription-closerdao.vercel.app/subscriptions

**Comment by marektucek** [comment]
1. I have an account, though Im not logged in. Im forced to signup without any option to signin included in the flow (ofc I can signin from the side bar as usual).

**Comment by marektucek** [comment]
2. In the /summary I feel like we should include more of the perks, not just Stays. @daneel

**Comment by marektucek** [comment]
@valieff when I'm already on paid subscription, clicking the Subscriptions button from the menu leads to My subscriptions (/settings/subscriptions), not to the list of possible subscriptions (/subscriptions). This way I can't browse other subscriptions and choose a different one that I currently have.

**Comment by valieff** [comment]
> @valieff when I'm already on paid subscription, clicking the Subscriptions button from the menu leads to My subscriptions (/settings/subscriptions), not to the list of possible subscriptions (/subscriptions). This way I can't browse other subscriptions and choose a different one that I currently have.

Let's discuss what a user with a paid plan should see when goes to /subscriptions during next standup.

Possible solutions:
- List of subscription plans with buttons modified to "Manage subscription". Upon button click the user goes to /settings/subscriptions
- Redirect to /settings/subscriptions. The logic behind this is that if the user has a paid plan, the only option for him is to upgrade to the remaining paid plan. This is what is implemented right now.
- Other ideas
