### ISSUE TITLE
Booking for event

### ISSUE THREAD

**Issue by marektucek** [closerdao/closer-ui#118]
Event page:

Admin: Separate out event.fee & accomodation.fee

Booking flow:

Book event -> /bookings/create/dates?event=eventID
booking/dates -> show events, if select date with event change to event booking
Booking/questions: hide if user.diet, user.mattress is set
bookings/summary - add event ticket costs
booking/checkout If api.credits.count > 0 - show credit discount, add credits: Number to booking call
checkout: up-sell checkbox to get subscription

**Comment by marektucek** [comment]
**User story**
As an authenticated user, I want to be able to book for events directly from the events list.

https://www.figma.com/file/zr7ncUdHTsMEv5haySrGTZ/TDF-Design-System-2.0?node-id=423-1853&t=WlQxC8VA0M6wdhw7-4

Scenario 1:
An authenticated user sees a list of events in /events. He browses, chooses one and clicks "get a ticket" button. He is redirected to a booking flow, but the dates are already pre-selected according to the event specs. He completes the flow and in the checkout the event ticket price is added to the total.

Scenario 2:
an unauthenticated user arrives at the /events page. He is prompted to log in/subscribe before he can buy a ticket for that event.

Variations:
- the user can choose whether to buy a 1 day / full ticket
- the user selects dates in the calendar and the ticket price is calculated according to the event specs provided by the event creator (each day can have a different price)

- the user is first prompted to sign in / sign up when viewing events, then prompted to subscribe if his tier is not high enough

**Comment by marektucek** [comment]
have a discussion about the event ticket. So far it doesnt make much sense to me:
1) user books for full length, comes at the beginning, leaves at the end, everyone is happy.
2) user wants to come for half of the event. Nobody is happy.
3) user wants to come before the event. Nobody is happy.
4) user wants to stay after the event. Nobody is happy.

**Comment by marektucek** [comment]
final comments @valieff 
- the input field for discount code should appear only when the "i have a discount code" is ticked https://www.figma.com/file/zr7ncUdHTsMEv5haySrGTZ/TDF-Design-System-2.0?node-id=644-4161&t=ZR0sS6isU2wawQqb-4
- also there should be the "Success / Something went wrong" confirmation text
- only one ticket (Full pass) for now, we might add other options later
- checkout for now completely excluding the "Redeem your stays" box, we'll add it next week with other stays pages

**Comment by marektucek** [comment]
testing:

**Comment by marektucek** [comment]
![Image](https://user-images.githubusercontent.com/94184807/234269584-d4fd9773-833b-44f6-8642-d8fbd34f228d.png)

missing a confirmation message if the code was or wasnt accepted (design [here](https://www.figma.com/file/zr7ncUdHTsMEv5haySrGTZ/TDF-Design-System-2.0?node-id=644-4161&t=wQ8FMx61ieFAp8Vk-4)

**Comment by marektucek** [comment]
![Image](https://user-images.githubusercontent.com/94184807/234270002-356c395f-7d43-4191-bd19-4a29c153fc99.png)

Im able to book for any date, date could be picked from calendar freely. It should be restricted to the event's date.
Im booking for Dummy Event

**Comment by marektucek** [comment]
Unauthenticated user event booking - forces me to sign in to book, works fine. doesnt feel like tearing me out from the flow, which is good.

**Comment by marektucek** [comment]
![Image](https://user-images.githubusercontent.com/94184807/234279579-2eb4d66a-1012-4f56-bbf0-f6d0e61e2214.png)



![Image](https://user-images.githubusercontent.com/94184807/234279689-a7ca41ce-3e7c-46a9-b827-9792ec21307c.png)

Im shown as a member automatically after signing up even though the admin interface says im not a member.

**Comment by marektucek** [comment]
![Image](https://user-images.githubusercontent.com/94184807/234282236-174232a7-9b6a-42d6-9bce-398afd34806b.png)

volunteer Pending card canceling - placeholder text.

**Comment by marektucek** [comment]
![Image](https://user-images.githubusercontent.com/94184807/234282915-fd588318-bf10-44ee-a71b-374701460c66.png)

Open card canceling - says it will refund me money even though I havent paid (not even completed) the booking.

**Comment by valieff** [comment]
> * also there should be the "Success / Something went wrong" confirmation text



> ![Image](https://user-images.githubusercontent.com/94184807/234270002-356c395f-7d43-4191-bd19-4a29c153fc99.png)
> 
> Im able to book for any date, date could be picked from calendar freely. It should be restricted to the event's date. Im booking for Dummy Event

Fixed

**Comment by valieff** [comment]
> ![Image](https://user-images.githubusercontent.com/94184807/234282915-fd588318-bf10-44ee-a71b-374701460c66.png)
> 
> Open card canceling - says it will refund me money even though I havent paid (not even completed) the booking.

Should work now

**Comment by valieff** [comment]
> ![Image](https://user-images.githubusercontent.com/94184807/234282683-6ff2e019-0410-4193-a35e-e82375801024.png)
> 
> double check if the refund calculation is correct.

Tests definitely need to be added for that, will try to do it during clean-up

**Comment by valieff** [comment]
> ![Image](https://user-images.githubusercontent.com/94184807/234279579-2eb4d66a-1012-4f56-bbf0-f6d0e61e2214.png)
> 
> ![Image](https://user-images.githubusercontent.com/94184807/234279689-a7ca41ce-3e7c-46a9-b827-9792ec21307c.png)
> 
> Im shown as a member automatically after signing up even though the admin interface says im not a member.

We have some confusion with terms here. "Member" role is assigned by an admin after the user meets certain criteria. "Member" in navigation bar does not mean you have a "Member" role assigned to you. It is hardcoded at the moment.

**Comment by valieff** [comment]
> final comments @valieff
> 
> * the input field for discount code should appear only when the "i have a discount code" is ticked https://www.figma.com/file/zr7ncUdHTsMEv5haySrGTZ/TDF-Design-System-2.0?node-id=644-4161&t=ZR0sS6isU2wawQqb-4
> * also there should be the "Success / Something went wrong" confirmation text
> * only one ticket (Full pass) for now, we might add other options later
> * checkout for now completely excluding the "Redeem your stays" box, we'll add it next week with other stays pages

Let's discuss the discount code form functionality at the next standup. We may want to simplify this form.

**Comment by marektucek** [comment]
https://github.com/closerdao/closer-ui/issues/118#issuecomment-1522087366

the date is restricted now, but once i choose a different date (in range <event start, event end>) it cannot be changed back. This is for both the start and end calendars.

**Comment by marektucek** [comment]
when I go to finish booking through an Open ticket, I land in /summary. If I hit the Back button, i get a flash of /aboutyou and immediately return to /summary. If I keep hitting the Back button a lot, Im able to go back to /dates

**Comment by marektucek** [comment]
![Image](https://user-images.githubusercontent.com/94184807/234363383-d09e5f7b-932f-4403-8d33-34a7ebec5f23.png)

I have just paid for my Confirmed booking and this is shown. Especially the last line is a problem, that I can now pay for my stay when I just did

**Comment by valieff** [comment]
> [#118 (comment)](https://github.com/closerdao/closer-ui/issues/118#issuecomment-1522087366)
> 
> the date is restricted now, but once i choose a different date (in range <event start, event end>) it cannot be changed back. This is for both the start and end calendars.

Fixed in https://github.com/traditionaldreamfactory/traditionaldreamfactory.com/pull/50

On Safari it is not apparent the the dates outside the event dates are blocked (they are not greyed out), but they are. This is because we are using the browser default date picker. Probably we should switch to some good looking date picker React component which will have better styling out of the box.
