### ISSUE TITLE
1-day tickets for events

### ISSUE THREAD

**Issue by marektucek** [closerdao/closer-ui#138]
will be specified by the event creator, fixed for a specific date without letting the user pick the date (e.g. full ticket + saturday ticket)

**Comment by marektucek** [comment]
![Image](https://user-images.githubusercontent.com/94184807/234543896-5f05b64c-7240-46ca-8955-3fd7af393ddd.png)

Unaunthenticated user, selected 1-day ticket, clicked Search

**Comment by marektucek** [comment]
![Image](https://user-images.githubusercontent.com/94184807/234544766-eb9217f4-9948-425e-a235-2b2d1679799d.png)

If I select the 1-day ticket and go through the flow until checkout and then click on Back to get back to the beginning, the Tickets are not visible

**Comment by marektucek** [comment]
![Image](https://user-images.githubusercontent.com/94184807/234550456-15f85e4a-8b14-43bb-941a-76fb54f8a8b8.png)

I bought a single day ticket and the email says I'll be staying for 2 days. We need a new email sending just the ticket if it's a single day ticket.

**Comment by marektucek** [comment]
![Image](https://user-images.githubusercontent.com/94184807/234563174-99121284-5f1d-47ed-b40b-8d53cadb8b61.png)

If im not logged in, this Buy Ticket button should instead be "Subscribe to access". Unaunthenticated user should not be able to get inside the booking flow.

**Comment by valieff** [comment]
> ![Image](https://user-images.githubusercontent.com/94184807/234563174-99121284-5f1d-47ed-b40b-8d53cadb8b61.png)
> 
> If im not logged in, this Buy Ticket button should instead be "Subscribe to access". Unaunthenticated user should not be able to get inside the booking flow.

I think we decided that unauthorised users should be able to see the prices / availability / descriptions of events / volunteer / accommodation options at one of our standups. Only force sign in / sign up as late as possible during the flow. But I'm not 100% sure about that
