### ISSUE TITLE
Checkout with Carrots

### ISSUE THREAD

**Issue by marektucek** [closerdao/closer-ui#140]
**User story**
As a user, I want to be able to use my Slumber Berries (credits) to pay for accomodation booking.

AC: 
- the /checkout contains a box with Slumber Berries
- when selected, the carrots provide discount to the accomodation price
- when used, the # of carrots get subtracted from the user

https://www.figma.com/file/zr7ncUdHTsMEv5haySrGTZ/TDF-Design-System-2.0?node-id=444-2982&t=vUgvS6N0GoV2HVf8-4

- enable checkout with carrots only if they pay for the entire accommodation (disable if user books for X nights and has Y carrots when X > Y)
- mimic the prices of $TDF bookings

**Comment by closerearth** [comment]
APIs:

- GET /stays/credit to get the number of credits available. If credits > booking.rentalToken - the "apply button you be active" (if not we should just hide the card I think)

To apply the credit:
1. POST /bookings/:id/update-payment `{ useCredits: true }` (ps you can also switch a booking to use token using the same endpoint with `{ useTokens: true }`)
This will return an updated booking object with a new total that discounts the accommodation fee that can be display to user.
2. when the use hits Apply, POST /bookings/:id/credit-payment - that will insert a new credit expense entry (thus reducing available credits), and update the booking status to `credits-paid`
3. The POST /bookings/payment will work for `credit-paid` booking to complete the booking.

**Comment by marektucek** [comment]
![Image](https://github.com/closerdao/closer-ui/assets/94184807/3f3343a6-5b6e-4952-971a-c3dd448f4a46)

Are we calculating the price correctly? This is for the test event, that's one night in van parking, for €30? It just slapped me in the face that here 0.5carrot = €30, which is a great deal for the carrot.
