### ISSUE TITLE
Link TDF Visitor guide to checkout

### ISSUE THREAD

**Issue by marektucek** [closerdao/closer-ui#147]
In /checkout, the link to TDF Visitor guide lead nowhere. Add the Visito Guide link here. https://docs.google.com/document/d/198vWYEQCC1lELQa8f76Jcw3l3UDiPcBKt04PGFKnUvg/edit

**Comment by valieff** [comment]
fixed: https://traditionaldreamfactory-git-fix-volunteer-visi-854a39-closerdao.vercel.app
or https://dev.traditionaldreamfactory.com if first link doesn't work
