### ISSUE TITLE
Report a bug in menu

### ISSUE THREAD

**Issue by marektucek** [closerdao/closer-ui#168]
Add a small redirect to a bug report form, design here: https://www.figma.com/file/zr7ncUdHTsMEv5haySrGTZ/TDF-Design-System-2.0?type=design&node-id=559-6039&t=FfX6C3EvRdFuLVpS-4

bug report form link: https://tally.so/r/nPD171

**Comment by valieff** [comment]
Report a bug link is live: https://www.traditionaldreamfactory.com
