### ISSUE TITLE
Store booking state in URL

### ISSUE THREAD

**Issue by closerearth** [closerdao/closer-ui#18]
In the first steps of booking, state  should be kept in URL (dates, adults etc - the search settings) - then upon selecting a listing, the booking is created and so we should reflect the ID in the URL so that a user can refresh the page etc.

## URLs

- /bookings should show the list of "My bookings"
- /bookings/:id should show the booking details.  If booking is not in guest-ready state, display additional status description (see below)
- /bookings/:id/checkout should show the checkout page for that booking. If the booking status is not "open", then should redirect to /bookings/:id to show the index summary instead. Upon completion of payment, redirect to /booking/:id
- /bookings/:id/questions should show the questions page for that booking
- /bookings/:id/cancel should show the  booking cancellation page
- /bookings/:id/summary should show the booking summary - if booking.status != "open" you can redirect to the index /bookings/:id to show  the index summary instead.
- /bookings/create/dates should show the dates + guest selector
- /bookings/create/accommodation?start=2022-01-01&end=2022-02-01&adults=5&infant=3 should be the page to show available listings
- /bookings/requests is the space-host page

## Loading booking page by booking.status

When I open /booking/:id, if status is open or tokens-staked, redirect to the appropriate page:

- open: /booking/:id/questions (or /booking/:id/summary if questions are set)
- tokens-staked /booking/:id/checkout - Should show the tokens as already staked, and only need fiat payment

### Non guest ready Status Descriptions

cancelled: Your booking was cancelled.
rejected: Your booking was rejected by space-host
pending: Your booking is awaiting confirmation from space-host

### Guest ready states

If the booking is in a guest-ready state, let's display additional information (based on status):

status = confirmed & booking start in less than 3 days: Pack your bags! [check in instructions] [TDF today whatsapp group]
status = checked-in & booking end > now: We hope you are enjoying your stay! [TDF today whatsapp group]
status = checked-in & booking end < now OR status = checked-out: We hope you enjoyed your stay. [Give us your feedback]

**Comment by sorokinvj** [comment]
what would be the design for "tokens-staked /booking/:id/checkout -  Should show the tokens as already staked, and only need fiat payment"?

**Comment by sorokinvj** [comment]
Could I please see the design for "display additional information" for Guest ready states?

**Comment by juliencharrel** [comment]
@daneelminev Need to mock the last 2 guest ready states

**Comment by juliencharrel** [comment]
@sorokinvj checked-in is a state

![Image](https://user-images.githubusercontent.com/3933420/206500235-6d067339-a75d-4e18-af31-be0a01231ba0.png)

**Comment by daneelminev** [comment]
@sorokinvj 

![The life of a booking card](https://user-images.githubusercontent.com/112096992/207070026-2dc8a6b4-f54b-4e00-a8f1-fc1abd1feccd.png)
