### ISSUE TITLE
Add total tickets count to event page

### ISSUE THREAD

**Issue by closerearth** [closerdao/closer-ui#19]
- Next to the profile pictures of the members going to an event, we should show a "+XX" badge of how many tickets have been purchased so that you can see how many people are attending.
- This should be compiled as text in the mouseover title of the section: I.e. "John, Sarah and 23 others are attending the event"
- If this is a free event (event.paid = false) then display event.attendees.length instead.

**Comment by juliencharrel** [comment]
Not sure where that should be done, in closer or somewhere else @closerearth ?
