### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by closerearth** [closerdao/closer-ui#301]
Generate graphs for all metrics collected:
- revenue 
- funnel (signups > subscriptions tiers > token sales)
- Token sales
- Energy consumption (smarthoods)
- Signups
- Water consumption (grey, well, city)
- Bookings

**Comment by francaye** [comment]
general notes from MOOS (18 june 2024)

- the 3 sections are perfect
- they see great value in a dashboard

BOOKINGS: the arriving today and departing today are great, current in-house is good to have but not so relevant. For them, having a 4th section here with events would be great. Probably linking to a calendar (very important to them!) where you can have a good overview of availability for events and hospitality
- * calendar: it would be cool to have a tool like 70% booked in July.
- add numbers to all graphs


REVENUE:
- change from reservations to applications?
- can leave the Vybe revenue, but currently is not very important
- add numbers to all graphs
- food is not relevant for moos (but we can keep it)
- add investments/donations?
- have a graph for costs as well (future dev)

METRICS:
- matching the data, I imagine having a bar for each metric and mixing them to make clear form where the booking comes from (either from the platform or an admin-external event)
- no wallet of tokens for moos, but we can keep it 

OTHER FEATURE REQUESTS:
- have a way to send messages to individuals or teams inside the platforms
- see the teams, message them and understand availability (-hey cleaning team, who is available tomorrow at 2pm?)
- calendar would come here as well
- nice to have automated tasks for the day as well
- referral program is a priority for them: 
MOOS https://docs.google.com/forms/d/1h3pxn9gqIQoeqEyTCcZDcgCAxPCw83R9VDlEYkprQz0/viewform?edit_requested=true
TDF 
https://docs.google.com/document/d/1WWKj9Hc28k-fnOeqRIOIS3grqgtRS7U9qUJFBW5G5YM/edit#heading=h.5950hiw7jdc3
