### ISSUE TITLE
Make "Food" as an option on the bookings

### ISSUE THREAD

**Issue by closerearth** [closerdao/closer-ui#332]
Let's remove the mandatory utility costs from bookings, and instead add a step in the checkout flow where users can check or uncheck "food" to include in their booking.
- add a foodPrice to booking. Also add `foodOption: [enum] ['basic', 'chef', 'no_food']`
- add foodPriceBasic, foodPriceChef prices to booking config
- When creating an event, event creator can chose to set food option to: `basic` (current 12€), `chef` (if set in config, something like 18€), `no_food`, `default` (default let's user chose).
- In the booking checkout, add a Food option ('basic' or 'no_food'). Display a mini photo gallery and description of what it includes. If `no_food` is selected - show a disclaimer that there is only a basic outdoor kitchen provided and no access to communal kitchen.
- For volunteers, they can chose to pay or not for food. If they opt out of food, then their total booking cost is 0 and they can skip the payment step for the booking (goes straight to 'paid' when then click confirm).
- In the event checkout, the food option is automatically set to whatever the event creator decided. If it's `default` let the user chose.

**Comment by valieff** [comment]
Add new 'food' field. Make optional. Allow to show/hide food option in config.  (title, description text, photos fields).

If food selected, show photo gallery for food. 

Custom food price for events. (stage 2)
