### ISSUE TITLE
[BUG] Fiat payment stuck

### ISSUE THREAD

**Issue by marektucek** [closerdao/closer-ui#92]
![Image](https://user-images.githubusercontent.com/94184807/224946770-ff250791-9a16-4f7d-915f-f95b8f660069.png)

fiat payment is stuck. I know this is not the final payment gate, but please check anyway if it will work as intended when released

**Comment by sorokinvj** [comment]
@marektucek all good on my side! please share as much info about your browser, link you used, etc 

<img width="633" alt="Screenshot 2023-03-19 at 20 31 31" src="https://user-images.githubusercontent.com/4914235/226207273-0a3474b4-99aa-4a91-896a-f51a948df11c.png">

**Comment by sorokinvj** [comment]
Here is what I meant by dev tools, you could open them in Chrome with cmd+option+I (at the same time)
https://www.awesomescreenshot.com/video/15949631

**Comment by sorokinvj** [comment]
Here is another example - https://www.awesomescreenshot.com/video/15949672 this helped me understand that I am testing the wrong webapp:)

**Comment by sorokinvj** [comment]
wait, traditionaldreamfactory is using live Stripe key, which means test card 4242 won't work anymore
