### ISSUE TITLE
Subscriptions - overarching base ticket

### ISSUE THREAD

**Issue by marektucek** [closerdao/closer-ui#94]
Design week 3, UI week 4

store credit card, bill monthly
automate

addpaymentmethod function, store on user. Settings page where users can see their payment methods
recurring payment (stripe? investigate). subscription integration with stripe
user.subscription, valid until Date, start date, user.subscription.tier
cancel subscription page in settings or change type, manage

+UXUI stuff

**Comment by marektucek** [comment]
!describe functionality from User perspective, break into stories

**Comment by sorokinvj** [comment]
How this ticket should be written, so it become the single source of truth for everyone in the team (FE lead perspective)

[clear concise definition of the functionality from the perspective of user]: 
**As an unauthenticated user I want to have the ability to buy TDF subscription with my credit card**

Scenario 1
Unauth User goes to the page /subscription, he sees 3 options. Each of the option includes:
- subscription name
- detail 1
- .... 
- detail X
- price 
- button "Buy me"
"When user clicks the button "Buy" he is redirected to Stripe hosted checkout. Or the magic modal appears which contains 2 buttons - confirm and cancel. Or a special section is rendered with the input for the credit card." - this has to be researched based on UX best practices that converts guests to users, non-payed strangers to people who spend money on something valuable. 

When you say "also in the Settings it should be possible to up/down/cancel subscription" I expect you write at least one story in the format above with some details for each action: up, down and cancel.

**Comment by sorokinvj** [comment]
what @closerearth was saying on a call about the monthly job - to fulfil active subscriptions (topup credits, do smth else) - is a very important design consideration, we should plan this very carefully as this is the product people are buying and we are responsible for delivery.
